default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: valley_first_heroku-development

test:
  <<: *default
  database: valley_first_heroku-test

production:
  <<: *default
  database: valley_first_heroku-heroku
